/**
 * types.ts — Shared TypeScript types for the entire application.
 *
 * Organized into four sections:
 *   1. Express augmentation  — adds requestId to the Request object
 *   2. DB row shapes         — mirror PostgreSQL table columns exactly
 *   3. HTTP layer types      — request bodies and unified response shapes
 *   4. Result<T> pattern     — typed service return values (no exceptions for
 *                              expected failures like 409 or 404)
 *   5. DB parameter objects  — typed arguments for db/ layer insert functions
 */

// ─── 1. Express augmentation ──────────────────────────────────────────────────
declare global {
  namespace Express {
    interface Request {
      /**
       * UUID generated by the requestId middleware in index.ts.
       * Included in every log line so a single request can be traced across
       * log entries even under concurrent load.
       */
      requestId: string;
    }
  }
}

// ─── 2. DB row shapes ─────────────────────────────────────────────────────────

export interface UserRow {
  id:            number;
  email:         string;
  password_hash: string;
  full_name:     string;
  phone:         string | null;
  role:          'patient' | 'doctor';
  created_at:    Date;
}

export interface ClinicRow {
  id:         number;
  doctor_id:  number;
  name:       string;
  specialty:  string;
  is_active:  boolean;
  created_at: Date;
}

export interface ServiceRow {
  id:               number;
  clinic_id:        number;
  name:             string;
  description:      string | null;
  duration_minutes: number;
  price:            string | null; // PostgreSQL DECIMAL is returned as string by pg
  is_active:        boolean;
  created_at:       Date;
}

export interface ReservationRow {
  id:                    number;
  clinic_id:             number;
  patient_id:            number;
  service_id:            number;
  start_time:            Date;
  end_time:              Date;
  status:                'confirmed' | 'cancelled' | 'completed';
  processed_by_instance: string | null;
  created_at:            Date;
}

export interface ReservationJobRow {
  id:                    number;
  clinic_id:             number;
  patient_id:            number;
  service_id:            number;
  start_time:            Date;
  end_time:              Date;
  status:                'pending' | 'processing' | 'completed' | 'failed';
  result_reservation_id: number | null;
  created_at:            Date;
  processed_at:          Date | null;
}

// ─── 3. HTTP layer types ──────────────────────────────────────────────────────

/** Validated request body accepted by all 4 POST /reservations/* endpoints. */
export interface CreateReservationBody {
  clinic_id:  number;
  patient_id: number;
  service_id: number;
  /** ISO 8601 string, e.g. "2025-06-10T10:00:00Z" */
  start_time: string;
}

/**
 * Unified response shape returned by all 4 concurrency strategies.
 * The `strategy` field names the mechanism so a client (or k6) can
 * confirm which endpoint handled the request.
 */
export interface ReservationResponse {
  reservation_id:        number;
  clinic_id:             number;
  patient_id:            number;
  start_time:            Date | string;
  end_time:              Date | string;
  processed_by_instance: string | null;
  strategy:              'naive' | 'pessimistic' | 'distributed' | 'queued';
}

// ─── 4. Result<T> pattern ─────────────────────────────────────────────────────

/**
 * A discriminated union that separates successful outcomes from expected
 * business-logic failures (409 conflict, 404 not found, 503 busy).
 *
 * Services return Result<T> instead of throwing for expected conditions,
 * making the caller (the route handler) explicitly aware of both paths.
 * Unexpected errors (DB connection failures) are still thrown — they
 * propagate through asyncHandler to the global error middleware.
 *
 * Example in a route:
 *   const result = await naiveService.book(body, req.requestId);
 *   if (!result.ok) {
 *     res.status(result.status).json({ error: result.message, code: result.code });
 *     return;
 *   }
 *   res.status(201).json(result.value);
 */
export type Result<T> =
  | { ok: true;  value: T }
  | { ok: false; status: number; code: string; message: string };

export function ok<T>(value: T): Result<T> {
  return { ok: true, value };
}

export function fail<T = never>(
  status:  number,
  code:    string,
  message: string,
): Result<T> {
  return { ok: false, status, code, message };
}

// ─── 5. DB parameter objects ──────────────────────────────────────────────────

export interface InsertReservationParams {
  clinicId:    number;
  patientId:   number;
  serviceId:   number;
  startTime:   string; // ISO string
  endTime:     string; // ISO string
  processedBy: string; // config.instanceId (+ fencing token for distributed)
}

export interface InsertJobParams {
  clinicId:  number;
  patientId: number;
  serviceId: number;
  startTime: string;
  endTime:   string;
}
